public class Ejercicio9Tema1{
  public static void main(String[]args){
    
    System.out.println();
   
    System.out.printf("%20s %21s","██","██");
    System.out.println();
    System.out.printf("%22s %17s","██","██");
    System.out.println();
    System.out.printf("%22s %17s","██","██");
    System.out.println();
    System.out.printf("%20s","                  ████████████████████████");
    System.out.println();
    System.out.printf("%20s","                  ████████████████████████");
    System.out.println();
    System.out.printf("%18s","██");
    
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.println();
    System.out.printf("%18s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.println();
    System.out.printf("%14s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf(" %25s" ,"Jesús Gutiérrez");
    System.out.println();
    System.out.printf("%14s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%25s","1º DAM");
    System.out.println();
    System.out.printf("%14s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.println();
    System.out.printf("%14s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%14s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.println();
    System.out.printf("%22s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%10s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","┃");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","┃");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","┃");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","┃");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","✥");
    System.out.println();
    System.out.printf("%29s %1s","✥","✥");
    System.out.println();
    System.out.printf("%28s %1s %1s","✥","✥","✥");
    System.out.println();

  }
}
