public class Ejercicio10Tema1{
  public static void main(String[]args){
    
    System.out.println();
   
    System.out.printf("%26s %20s","\033[31m██","██");
    System.out.println();
    System.out.printf("%22s %17s","██","██");
    System.out.println();
    System.out.printf("%22s %17s","██","██");
    System.out.println();
    System.out.printf("%20s","                  ████████████████████████");
    System.out.println();
    System.out.printf("%20s","                  ████████████████████████");
    System.out.println();
    System.out.printf("%18s","██");
    
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.println();
    System.out.printf("%18s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.println();
    System.out.printf("%14s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██\033[39;49m");
    System.out.printf(" %25s" ,"Jesús Gutiérrez");
    System.out.println();
    System.out.printf("%14s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
     System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.printf("%25s","1º DAM");
    System.out.println();
     System.out.printf("%14s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
     System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.println();
     System.out.printf("%14s","██");
    System.out.printf("%4s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%14s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%4s","██");
    System.out.println();
    System.out.printf("%22s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.printf("%10s","██");
    System.out.printf("%1s","██");
    System.out.printf("%1s","██");
    System.out.println();
    System.out.println();
    System.out.printf("%35s","\033[33m┃");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","┃");
    System.out.println();
    System.out.println();
    System.out.printf("%30s","┃");
    System.out.println();
    System.out.println();
    System.out.printf("%38s","┃\033[39;49m");
    System.out.println();
    System.out.println();
    System.out.printf("\033[36m %29s","✥");
    System.out.println();
    System.out.printf("%29s %1s","✥","✥");
    System.out.println();
    System.out.printf("%28s %1s %1s","✥","✥","✥ \033[39;49m");


  }
}
